### ISSUE TITLE
RabbitMQ Fails Using Defined USER & PASSWORD

### ISSUE THREAD

**Issue by MrAbdelaziz** [meysamhadeli/booking-microservices-expressjs#13]
hello, 
I appreciate the effort put into this project.

RabbitMQ fails to authenticate using defined USER and PASSWORD. Despite setting the credentials correctly in the configuration, authentication does not work as expected.

**Comment by meysamhadeli** [comment]
Hi, 
Your welcome :)
I updated the deployment [infrastructure.yaml](https://github.com/meysamhadeli/booking-microservices-expressjs/blob/main/deployments/docker-compose/infrastructure.yaml#L7) and please try again and the dashboard rabbitmq should work properly with default username: `guest` and password: `guest`.

**Comment by MrAbdelaziz** [comment]
> Hi, Your welcome :) I updated the deployment [infrastructure.yaml](https://github.com/meysamhadeli/booking-microservices-expressjs/blob/main/deployments/docker-compose/infrastructure.yaml#L7) and please try again and the dashboard rabbitmq should work properly with default username: `guest` and password: `guest`. also we had a **breaking change** in last version package `amqp` in file [rabbitmq-connection.ts](https://github.com/meysamhadeli/booking-microservices-expressjs/blob/main/src/building-blocks/rabbitmq/rabbitmq-connection.ts#L9) and I fixed that.

Hi Meysam,
First of all, thank you for taking the time to update the project.

When configuring RabbitMQ with custom credentials using Docker Compose, the application fails to establish a connection. Debug logs indicate that the configuration object is undefined in the `createConnection `method of `rabbitmq-connection.ts`.

Docker Compose Configuration:


```
rabbitmq:
  container_name: rabbitmq
  image: rabbitmq:management
  restart: unless-stopped
  environment:
    - RABBITMQ_DEFAULT_USER=root
    - RABBITMQ_DEFAULT_PASS=password123
  ports:
    - "5672:5672"
    - "15672:15672"
  networks:
    - booking
```

.env.dev File:

```
# RabbitMQ Configuration
RABBITMQ_Host=172.21.0.2
RABBITMQ_PORT=5672
RABBITMQ_USERNAME=root
RABBITMQ_PASSWORD=password123
RABBITMQ_EXCHANGE=booking
```
